import {StormTimeline} from './weather.mjs';
import {matchReference} from './match.js';
import {createFeedback} from './feedback.js';
import {refineHero} from './hero.js';
import * as T from 'three';
import {createVillage} from './scene.js';
import {buildProps} from './props.js';
import {upgradeVillage} from './environment.js';
import {Soundscape} from './audio.js';
import {Expedition,ITEMS,LAMPS,ACTIVE,CHECKPOINT,validateSave,movePlayer,groundHeight,collides} from './core.mjs';
const $=id=>document.getElementById(id),testMode=new URLSearchParams(location.search).has('test'),qaMode=new URLSearchParams(location.search).has('qa'),SAVE_KEY=testMode?'rainwell-test-v1':qaMode?'rainwell-qa-v1':'rainwell-save-v1',SETTINGS_KEY=testMode||qaMode?'rainwell-qa-settings-v1':'rainwell-settings-v1';
let storageAvailable=true;function read(key){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}}function store(key,v){try{localStorage.setItem(key,JSON.stringify(v))}catch{storageAvailable=false}}function clearSave(){try{localStorage.removeItem(SAVE_KEY)}catch{storageAvailable=false}}
let saved=validateSave(read(SAVE_KEY)),game=new Expedition(saved),v,props,loaded=false,yaw=0,pitch=0,sensitivity=1,hold=0,interaction=null,time=0,fallTime=0,fallStart=null,subtitleUntil=0,nearShown=-1,farShown=-1,lastSave=0,moving=false,sprint=false,dragging=false,menuTime=0,introTime=0,menuSettings=false;
const feedback=createFeedback(),weather=new StormTimeline();let threatUntil=0;
const audio=new Soundscape(),keys=new Set(),player={x:2,z:2.4},direction=new T.Vector3(),temp=new T.Vector3();const overlays=['menu','pause','journal','failure','ending','confirm'];
function hideOverlays(){overlays.forEach(id=>$(id).hidden=true)}
function subtitle(text,seconds=6,tier=0){if(!tier&&time<threatUntil)return;const el=$('subtitle');el.className=tier?'danger-caption tier-'+tier:'';if(tier)threatUntil=time+seconds;el.textContent=text;$('subtitle').style.opacity='1';subtitleUntil=time+seconds;}
function updateObjective(){const done=game.stage===3;$('objective').textContent=done?'回到水井。井边最后一盏灯还在等你。':ITEMS[game.stage].hint;$('progress-label').textContent=game.stage+' / 3';for(let i=0;i<3;i++){const el=$('slot-'+i);el.classList.toggle('found',i<game.stage);el.classList.toggle('current',i===game.stage);el.textContent=(['Ⅰ ','Ⅱ ','Ⅲ '][i])+['摇柄','钥匙','符牌'][i];}}
function saveGame(){if(game.phase==='complete')return;store(SAVE_KEY,game.snapshot());saved=game.snapshot();$('save-note').textContent=storageAvailable?'已找到的道具会自动保存。':'当前环境无法保存；离开后需要重新开始。';}
function menuView(){menuSettings=false;game.phase='menu';document.body.dataset.phase='menu';if(v){v.lightning.intensity=0;v.threat.uniforms.uLightning.value=0;}keys.clear();audio.pause();releasePointer();hideOverlays();$('menu').hidden=false;$('hud').hidden=true;$('fade').style.opacity='0';$('threat-vignette').style.opacity='0';$('start').textContent=saved?'继续寻找':'进入村庄';$('new-game').hidden=!saved;v.camera.fov=38;v.camera.updateProjectionMatrix();$('start').focus();}
function releasePointer(){if(document.pointerLockElement)document.exitPointerLock();dragging=false;}
function placeStart(checkpoint){player.x=checkpoint?CHECKPOINT.x:2;player.z=checkpoint?CHECKPOINT.z:2.4;yaw=checkpoint?0:.08;pitch=0;v.camera.position.set(player.x,groundHeight(player.x,player.z)+1.7,player.z);v.camera.rotation.order='YXZ';v.camera.rotation.set(pitch,yaw,0);v.camera.fov=65;v.camera.updateProjectionMatrix();}
async function start(){if(!loaded)return;document.body.classList.add('entering');setTimeout(()=>document.body.classList.remove('entering'),900);const fresh=!saved;game=new Expedition(saved);game.start();introTime=0;if(fresh&&!testMode)game.phase='intro';nearShown=farShown=-1;placeStart(game.stage>0);hideOverlays();$('hud').hidden=false;$('fade').style.opacity='0';keys.clear();interaction=null;hold=0;updateObjective();feedback.announce(game.stage);threatUntil=0;weather.reset(game.stage);updateHud();if(!testMode){await audio.start();}subtitle(game.phase==='intro'?'雷声停下之前，把东西带回来。〔空格跳过〕':game.stage?'灯还亮着。找回剩下的东西。':'只有灯柱下是安全的。先去集市，把摇柄带回来。',8);saveGame();}
function finishIntro(){if(game.phase!=='intro')return;game.phase='playing';placeStart(false);feedback.announce(game.stage);subtitle('只有灯柱下是安全的。先去集市，把摇柄带回来。',8);}
function pause(which='pause'){if(game.phase!=='playing')return;menuSettings=false;$('pause-title').textContent='暂歇';$('pause-note').textContent='雨还在下。此刻，黑暗不会逼近。';$('resume').textContent='继续寻找';$('to-menu').hidden=false;game.pause();keys.clear();hold=0;audio.pause();releasePointer();hideOverlays();$(which).hidden=false;if(which==='journal')$('journal-hint').textContent=game.stage<3?ITEMS[game.stage].extra:'三件东西已经齐了。回到井边，面对井口，按住 E 跳下。';saveGame();$(which==='journal'?'close-journal':'resume').focus();}
function openCoverSettings(){menuSettings=true;hideOverlays();$('pause').hidden=false;$('pause-title').textContent='声音与画面';$('pause-note').textContent='先听清雨声，再走进村庄。';$('resume').textContent='回到封面';$('to-menu').hidden=true;$('save-note').textContent='设置会自动记住。';$('volume').focus();}
async function resume(){if(menuSettings){menuView();return;}if(game.phase!=='paused')return;game.resume();hideOverlays();keys.clear();if(!testMode){await audio.start();}}
function fail(){saveGame();keys.clear();hold=0;releasePointer();audio.cue('failed');$('fade').style.opacity='1';$('hud').hidden=true;hideOverlays();$('failure').hidden=false;$('failure-progress').textContent=`已找到 ${game.stage} / 3 件物品。重试会保留道具，回到井边的安全灯下。`;$('retry').focus();}
async function retry(){if(!game.retry())return;placeStart(true);hideOverlays();$('hud').hidden=false;$('fade').style.opacity='0';keys.clear();hold=0;nearShown=-1;threatUntil=0;weather.reset(game.stage);updateObjective();feedback.announce(game.stage);if(!testMode){await audio.start();}interaction=null;updateHud();subtitle('你回到了灯下。已经找到的东西还在。',5);}
function requestNew(){hideOverlays();$('confirm').hidden=false;releasePointer();$('cancel-new').focus();}
function resetGame(){clearSave();saved=null;game=new Expedition();nearShown=farShown=-1;start();}
function segmentHits(a,b,r){let t0=0,t1=1;for(const [coord,min,max] of [['x','minX','maxX'],['z','minZ','maxZ']]){const d=b[coord]-a[coord];if(Math.abs(d)<1e-8){if(a[coord]<r[min]||a[coord]>r[max])return false;}else{let l=(r[min]-a[coord])/d,h=(r[max]-a[coord])/d;if(l>h)[l,h]=[h,l];t0=Math.max(t0,l);t1=Math.min(t1,h);if(t0>t1)return false;}}return t1>.05&&t0<.97;}
function visibleTarget(p,name){return !props.rects.some(r=>r.name!==name&&segmentHits(player,p,r));}
function getInteraction(){v.camera.getWorldDirection(direction);if(game.stage<3){const it=ITEMS[game.stage],p=temp.set(it.x,it.y,it.z).sub(v.camera.position),d=Math.hypot(it.x-player.x,it.z-player.z);if(d<=2.15&&p.normalize().dot(direction)>.9&&visibleTarget(it,['crank crate','cart','altar'][game.stage]))return {type:'item',index:game.stage,label:'拾取 '+it.name};}const d=Math.hypot(player.x,player.z+6);if(d<=2.65&&temp.set(-player.x,1.55-v.camera.position.y,-6-player.z).normalize().dot(direction)>.7&&visibleTarget({x:0,z:-6},'Hero_Well'))return {type:'well',label:game.stage===3?'按住，跃入井口':'井口被封住了'};return null;}
function interact(){if(game.phase!=='playing')return;interaction=getInteraction();if(interaction?.type==='item'){if(game.collect(player)){nearShown=farShown=-1;hold=0;interaction=null;saveGame();processEvents();updateObjective();props.update(game,time,-1);}}else if(interaction?.type==='well'&&game.stage<3)subtitle(`还缺 ${3-game.stage} 件东西。${ITEMS[game.stage].hint}`,7);}
function processEvents(){for(const e of game.drain()){if(e.type==='collected'){audio.cue('collect');feedback.announce(e.stage);audio.duck(3);subtitle(e.stage===3?'符牌已经回来了。回到井口。':'拿到了'+e.name+'。远处的灯开始闪烁……',7);saveGame();}if(e.type==='lightsOut'){audio.cue('warning');subtitle('又有灯熄灭了。井边的灯还亮着。',5);}if(e.type==='threat'){subtitle(['','身后多了一阵脚步。','它在靠近。回到亮着的灯下。','它就在身后。快回到灯下！'][e.tier],4,e.tier);audio.duck(2);}if(e.type==='failed')fail();}}
function beginFall(){if(!game.beginFall(player))return;fallTime=0;fallStart=v.camera.position.clone();keys.clear();releasePointer();audio.cue('warning');subtitle('回来。',2);$('interaction').hidden=true;}
function simulate(dt,input=null,realDt=dt){if(!loaded)return;dt=Math.min(.1,Math.max(0,dt));time+=dt;if(game.phase==='playing'){
 const k=input||{x:(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),z:(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0),sprint:keys.has('ShiftLeft')||keys.has('ShiftRight')};
 if(keys.has('ArrowLeft'))yaw+=dt*1.4;if(keys.has('ArrowRight'))yaw-=dt*1.4;if(keys.has('ArrowUp'))pitch=Math.min(1.25,pitch+dt);if(keys.has('ArrowDown'))pitch=Math.max(-1.25,pitch-dt);
 const len=Math.hypot(k.x,k.z);sprint=!!k.sprint&&len>0;const beforeX=player.x,beforeZ=player.z;if(len){const sp=(sprint?3.8:2.15)*dt,dx=(k.x*Math.cos(yaw)+k.z*Math.sin(yaw))/len*sp,dz=(-k.x*Math.sin(yaw)+k.z*Math.cos(yaw))/len*sp;movePlayer(player,dx,dz,props.rects);}moving=Math.hypot(player.x-beforeX,player.z-beforeZ)>.001;
 game.update(dt,player,sprint&&moving);processEvents();v.camera.position.set(player.x,groundHeight(player.x,player.z)+1.7+(moving?Math.sin(time*(sprint?15:10))*.018:0),player.z);v.camera.rotation.set(pitch,yaw,0,'YXZ');v.camera.updateMatrixWorld();interaction=getInteraction();if(interaction?.type==='well'&&game.stage===3&&keys.has('KeyE')){hold+=dt;if(hold>=1.5)beginFall()}else hold=0;
 if(game.stage<3){const it=ITEMS[game.stage],d=Math.hypot(player.x-it.x,player.z-it.z);if(d<5&&nearShown!==game.stage){nearShown=game.stage;subtitle(it.near,6);audio.cue('hint');}if(game.stageTime>80&&farShown!==game.stage){farShown=game.stage;subtitle(it.extra+' 按 Tab 可以辨认方向。',10);}}
 if(time-lastSave>12){saveGame();lastSave=time;}audio.update(dt,game,v.camera,moving,sprint,time);
 for(const event of weather.update(realDt,game.stage)){if(event.type==='thunder')audio.thunder(event.near,game.stage);}
 }else if(game.phase==='intro'){introTime+=dt;const t=Math.min(1,introTime/6),u=t*t*(3-2*t);v.camera.position.set(-7+8*u,2.2-.2*u,6-3.5*u);v.camera.lookAt(-.6+.6*u,2,-7+u);if(introTime>=6)finishIntro();}else if(game.phase==='falling'){fallTime+=dt;const approach=Math.min(1,fallTime/.8);v.camera.position.set(T.MathUtils.lerp(fallStart.x,0,approach),fallTime<.8?T.MathUtils.lerp(fallStart.y,1.85,approach):1.85-2.8*(fallTime-.8)**2,T.MathUtils.lerp(fallStart.z,-6,approach));v.camera.rotation.set(-Math.min(1.45,fallTime*.75),yaw,0,'YXZ');$('fade').style.opacity=String(Math.max(0,Math.min(1,(fallTime-1.4)/1.2)));if(fallTime>=3.2){game.finish();clearSave();saved=null;$('hud').hidden=true;hideOverlays();$('ending').hidden=false;$('ending-stats').textContent=`已找齐三件归井之物 · ${Math.floor(game.elapsed/60)} 分 ${Math.floor(game.elapsed%60)} 秒 · 重试 ${game.deaths} 次`;audio.pause();$('play-again').focus();}}
 feedback.update(['playing'].includes(game.phase)?dt:0,game,player,yaw);
 const flash=['playing','paused'].includes(game.phase)?weather.flash:0;v.lightning.intensity=flash*3.2;v.threat.uniforms.uLightning.value=flash;
}
function updateHud(){if(!loaded)return;if(document.body.dataset.phase!==game.phase)document.body.dataset.phase=game.phase;const d=game.danger/100;$('threat-vignette').style.opacity='0';v.threat.uniforms.uThreat.value=game.phase==='menu'?0:Math.pow(d,.85);
 const safety=game.safe?(game.danger>8?'灯下 · 它正在远离':'灯下 · 暂时安全'):game.danger>=85?'它就在身后':game.danger>=60?'脚步越来越近':game.danger>=25?'有脚步跟着你':'黑暗中';$('safety-text').textContent=safety;$('safety').classList.toggle('unsafe',!game.safe);$('safety').classList.toggle('critical',game.danger>=85);$('light-count').textContent=`灯火 ${game.activeLamps().length}${game.pending.length?' · 正在闪烁':''}`;
 $('interaction').hidden=!interaction||game.phase!=='playing';if(interaction)$('interaction-text').textContent=interaction.label;$('hold-track').hidden=!(interaction?.type==='well'&&game.stage===3);$('hold-fill').style.width=Math.min(100,hold/1.5*100)+'%';if(time>subtitleUntil)$('subtitle').style.opacity='0';v.setLamps(game.activeLamps(),game.pending,weather.time,game.stage);props.update(game,time,interaction?.type==='item'?interaction.index:-1);
}
function draw(){if(!loaded)return;updateHud();v.draw(time);}
async function init(){try{v=await createVillage($('stage'),p=>{$('load-progress').value=p;$('load-text').textContent=p<1?'正在穿过雨幕 · '+Math.round(p*100)+'%':'灯正在亮起。'});props=await buildProps(v);$('load-text').textContent='正在布置村庄街巷。';await upgradeVillage(v,props);refineHero(v);await matchReference(v);feedback.rects=props.rects;loaded=true;$('loader').hidden=true;const settings=read(SETTINGS_KEY)||{};if(Number.isFinite(settings.volume))$('volume').value=Math.max(0,Math.min(1,settings.volume));if(Number.isFinite(settings.sensitivity))$('sensitivity').value=Math.max(.4,Math.min(2,settings.sensitivity));if(['balanced','high'].includes(settings.quality))$('quality').value=settings.quality;applySettings();menuView();window.dispatchEvent(new Event('game-ready'));}catch(e){console.error(e);$('load-text').textContent='村庄加载失败。请刷新，或通过本地服务器打开。';}}
function applySettings(){sensitivity=+$('sensitivity').value;audio.setVolume(+$('volume').value);v?.setQuality($('quality').value,$('reflections').checked);store(SETTINGS_KEY,{volume:audio.volume,sensitivity,quality:$('quality').value});}
$('cover-settings').onclick=openCoverSettings;$('start').onclick=start;$('new-game').onclick=requestNew;$('confirm-new').onclick=resetGame;$('cancel-new').onclick=()=>{hideOverlays();$('menu').hidden=false};$('resume').onclick=resume;$('close-journal').onclick=resume;$('retry').onclick=retry;$('to-menu').onclick=()=>{saveGame();menuView()};$('failure-menu').onclick=menuView;$('play-again').onclick=resetGame;
for(const id of ['volume','sensitivity','quality','reflections'])$(id).oninput=applySettings;
addEventListener('keydown',e=>{if(e.code==='Escape'&&menuSettings){e.preventDefault();resume();return;}if(game.phase==='intro'&&['Space','KeyE','Escape'].includes(e.code)){e.preventDefault();finishIntro();if(e.code==='Escape')pause();return;}if(['KeyW','KeyA','KeyS','KeyD','KeyE','ShiftLeft','ShiftRight','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code)&&game.phase==='playing'){keys.add(e.code);e.preventDefault();if(e.code==='KeyE'&&!e.repeat)interact();}if(e.code==='Escape'){if(game.phase==='playing')pause();else if(game.phase==='paused')resume();}if(e.code==='Tab'){if(game.phase==='playing'){e.preventDefault();if(!e.repeat){feedback.request();audio.cue('hint');}}else if(game.phase==='paused'&&!$('journal').hidden){e.preventDefault();resume();}}});
addEventListener('keyup',e=>{keys.delete(e.code);if(e.code==='KeyE')hold=0});addEventListener('blur',()=>{if(game.phase==='intro')finishIntro();if(game.phase==='playing'&&!testMode)pause();keys.clear()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.phase==='playing')pause()});
addEventListener('mousedown',e=>{if(e.button===0&&e.target===v?.renderer.domElement&&game.phase==='playing'){dragging=true;e.preventDefault();}});addEventListener('mouseup',e=>{if(e.button===0)dragging=false});addEventListener('mousemove',e=>{if(!(e.buttons&1)){dragging=false;return;}if(game.phase==='playing'&&dragging){yaw-=e.movementX*.0018*sensitivity;pitch=T.MathUtils.clamp(pitch-e.movementY*.0018*sensitivity,-1.35,1.35);}});
let last=performance.now();function frame(now){requestAnimationFrame(frame);const frameMs=now-last,dt=Math.min(.1,frameMs/1000);last=now;if(!loaded)return;if(!testMode&&game.phase==='playing')v.adaptFrame(frameMs);if(document.hidden)return;if(!testMode||!window.gameTest?.manual)simulate(dt,null,Math.max(0,frameMs/1000));if(game.phase==='menu'){menuTime+=dt;v.camera.position.set(1+Math.sin(menuTime*.06)*.6,2.15,3.7);v.camera.lookAt(0,2,-6);time+=dt;}draw();}requestAnimationFrame(frame);init();
if(testMode)window.gameTest={manual:true,get ready(){return loaded},get modelStatus(){return props?.detailed},get state(){return {phase:game.phase,stage:game.stage,danger:game.danger,safe:game.safe,elapsed:game.elapsed,pending:game.pending,active:game.activeLamps(),player:{...player},hold,interaction,save:read(SAVE_KEY)}},canStand:p=>!collides(p,props.rects),get rects(){return props?.rects},get targets(){return ITEMS},get village(){return v},get feedback(){return feedback},get sound(){return audio},get itemMeshes(){return props?.items},start,step:(dt,input,realDt=dt)=>{simulate(dt,input,realDt);updateHud()},lookAt(x,y,z){v.camera.lookAt(x,y,z);const e=new T.Euler().setFromQuaternion(v.camera.quaternion,'YXZ');yaw=e.y;pitch=e.x;v.camera.updateMatrixWorld();interaction=getInteraction();updateHud();},interact,pressE:()=>keys.add('KeyE'),releaseE:()=>keys.delete('KeyE'),pause:()=>pause(),resume,retry,render:draw,get game(){return game}};

window.rainwell={get status(){return {version:"0.6.1",weather:{time:weather.time,nextIn:weather.next-weather.time,flashes:weather.flashes,thunders:weather.thunders,flash:weather.flash},ready:loaded,phase:game.phase,stage:game.stage,danger:game.danger,safe:game.safe,player:{...player},heading:{yaw,pitch},audio:audio.ctx?.state||"not-started",pointerLocked:!!document.pointerLockElement,models:props?.detailed,quality:$("quality").value};}};
